lib/tic_tac_toe_web/router.ex
defmodule TicTacToeWeb.Router do
  use TicTacToeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser_auth do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: TicTacToe.Token
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  scope "/", TicTacToeWeb do
    pipe_through :browser # Use the default browser stack

    get "/", GameController, :new
    resources "/sessions", SessionController, only: [:new, :create]

    # Don't autogenerate this route from Phoenix because it will assume we need an :id param.
    delete "/sessions", SessionController, :delete

    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", TicTacToeWeb do
    pipe_through :browser_auth
    resources "/games", GameController, only: [:index, :new, :create, :show]
  end

  # Other scopes may use custom stacks.
   scope "/api", TicTacToeWeb, as: :api do
     pipe_through :api

     resources "/sessions", Api.SessionController, only: [:create]
     resources "/games", Api.GameController, only: [:index, :show, :update]
     resources "/user_games", Api.UserGamesController, only: [:create]
   end
end

lib/tic_tac_toe_web/views/layout_view.ex
defmodule TicTacToeWeb.LayoutView do
  use TicTacToeWeb, :view
end

lib/tic_tac_toe_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fixed Game</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Raleway|Roboto" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <h4 class="nav-logo">Fixed Game</h4>

      <%= if Guardian.Plug.current_resource(@conn) do %>
        <div class="nav-right">
          <div class="row">
            <div class="col-sm-3">
              <%= link("Games", to: game_path(@conn, :index), class: "nav-link") %>
            </div>

            <div class="col-sm-6">
              <%= link("Log Out", to: session_path(@conn, :delete), method: :delete, class: "nav-link") %>
            </div>

            <div class="col-sm-6">
              <%= Guardian.Plug.current_resource(@conn).username %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="nav-right">
          <p class="nav-text">
            <%= link("Log In", to: session_path(@conn, :new), class: "nav-link login-link") %>
          </p>

          <p class="nav-text">
            <%= link("Sign Up", to: user_path(@conn, :new), class: "nav-link login-link") %>
          </p>
        </div>
      <% end %>
    </header>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <div id="alert-info"/>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->

    <%#NOTE: This has to go below main because react prevents the rest of the DOM from rendering...%>
    <%#Figure out why%>
    <%= if get_flash(@conn, :error) do %>
      <%= content_tag(:div, "", id: "alert-danger-mount", data: [content: get_flash(@conn, :error)]) %>
    <% end %>

    <%= if get_flash(@conn, :info) do %>
      <%= content_tag(:div, "", id: "alert-info-mount", data: [content: get_flash(@conn, :info)]) %>
    <% end %>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>